from dataclasses import dataclass, field
from typing import List, Optional
from .constants import TemplateTier

@dataclass
class RawAttackEvent:
    """
    Raw Attack Event - Pure data event generated by the Combat Engine
    This is the input for the Presentation System.

    Extended for StatisticsCollector integration:
    - Added roll_value for statistical analysis
    - Added *_after fields for post-attack state snapshots
    """
    # Basic Info
    round_number: int              # Current round number
    attacker_id: str               # Attacker Instance ID
    defender_id: str               # Defender Instance ID
    attacker_name: str             # Attacker Name
    defender_name: str             # Defender Name

    # Weapon Info
    weapon_id: str                 # Weapon Definition ID
    weapon_name: str               # Weapon Name
    weapon_type: str               # Weapon Type (Enum string)
    weapon_tags: List[str]         # Weapon Tags

    # Validation/Result
    attack_result: str             # MISS/DODGE/PARRY/BLOCK/HIT/CRIT
    damage: int                    # Final damage dealt

    # Context
    distance: int                  # Distance in meters
    attacker_will_delta: int       # Change in Attacker's Will
    defender_will_delta: int       # Change in Defender's Will

    # Skills
    triggered_skills: List[str]    # List of triggered skill IDs

    # Flags
    is_first_attack: bool          # Is this the first attack in the round?
    initiative_holder: str         # Who holds the initiative

    # Statistics Extension (for StatisticsCollector)
    roll_value: float = 0.0        # Original Roll value for distribution analysis
    en_cost: int = 0               # EN consumed for this attack

    # Post-attack state snapshots (optional, for detailed analysis)
    attacker_hp_after: int = 0     # Attacker's HP after attack
    attacker_en_after: int = 0     # Attacker's EN after attack
    attacker_will_after: int = 0   # Attacker's Will after attack
    defender_hp_after: int = 0     # Defender's HP after attack
    defender_en_after: int = 0     # Defender's EN after attack
    defender_will_after: int = 0   # Defender's Will after attack

@dataclass
class PresentationAttackEvent:
    """
    Presentation Attack Event - Complete audiovisual instruction for the frontend
    This is the output of the Presentation System.
    """
    # Event Classification
    event_type: str               # ACTION (Attacker) or REACTION (Defender)
    round_number: int             # Round number
    timestamp: float = 0.0        # Relative timestamp for playback
    
    # Content
    text: str = ""                # The narrative text to display
    display_tags: List[str] = field(default_factory=list) # Tags for UI highlighting (e.g., "CRITICAL", "BLOCK")
    
    # Visual Resources
    tier: TemplateTier = TemplateTier.T3_FALLBACK
    anim_id: str = "default_anim" # Animation Resource ID
    camera_cam: str = "cam_default" # Camera movement ID
    vfx_ids: List[str] = field(default_factory=list) # Visual Effects
    sfx_ids: List[str] = field(default_factory=list) # Sound Effects
    
    # Combat Data Update (Visual Only)
    damage_display: int = 0       # Damage number to pop up
    hit_location: str = "body"    # Visual hit location
    
    # References
    raw_event: Optional[RawAttackEvent] = None
    attacker_name: str = ""
    defender_name: str = ""
    weapon_name: str = ""
    attack_result: str = "" 

@dataclass
class PresentationAttackSequence:
    """
    Groups events for a single attack action (usually Action + Reaction).
    """
    attacker_id: str
    defender_id: str
    events: List[PresentationAttackEvent] = field(default_factory=list)

@dataclass
class PresentationRoundEvent:
    """
    Presentation Round Event - Grouping all events in a single round.
    Supports multiple attackers or follow-up attacks.
    """
    round_number: int
    context_events: List[PresentationAttackEvent] = field(default_factory=list) # e.g. Round start titles
    attack_sequences: List[PresentationAttackSequence] = field(default_factory=list)
    summary_events: List[PresentationAttackEvent] = field(default_factory=list) # e.g. Mecha destruction

    def get_all_events(self) -> List[PresentationAttackEvent]:
        """Returns all events in logical playback order."""
        events = []
        events.extend(self.context_events)
        for seq in self.attack_sequences:
            events.extend(seq.events)
        events.extend(self.summary_events)
        return events
